name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          
      - name: Build Docker image
        run: |
          docker build -t cholong_fe:1.0.1 .
          docker tag cholong_fe:1.0.1 ${{ secrets.DOCKERHUB_USERNAME }}/cholong_fe:1.0.1
            
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cholong_fe:1.0.1

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            sudo docker version
            sudo docker rm -f cholong_fe || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cholong_fe:1.0.1
            sudo docker run -d --name cholong_fe -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/cholong_fe:1.0.1 
            sudo docker ps -all
